# Generated by Django 2.2.1 on 2020-05-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_num', models.IntegerField()),
                ('module_num', models.IntegerField()),
                ('yt_link', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
