# Generated by Django 2.2.1 on 2020-06-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_auto_20200601_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='show_to',
            field=models.CharField(choices=[('all', 'all'), ('stu', 'stu'), ('sup', 'sup')], default='all', max_length=5),
        ),
    ]
